name: PixaMart
description: Pixamart

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+4

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  cached_network_image:
  image_gallery_saver:
  random_string:
  dio:
  flutter_wallpaper_manager: ^0.0.3
  flutter_cache_manager: ^3.1.2
  rive: ^0.8.4
  animated_splash_screen: ^1.2.0
  page_transition: ^2.0.5
  lottie: ^1.3.0
  flutter_speed_dial: ^6.0.0
  flutter_zoom_drawer: ^3.0.2
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  curved_navigation_bar: ^1.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^4.6.5
  liquid_progress_indicator_ns: ^1.0.0
  flutter_screenutil: ^5.5.3+2
  line_awesome_flutter: ^2.0.0
  google_fonts: ^3.0.1
  simple_animations: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/rive/1920-3835-start.riv
    - assets/rive/loading.riv
    - assets/rive/intro.riv
    - assets/rive/pull-to-refresh_community_demo.riv
    - assets/rive/App_intro.riv
    - assets/rive/Welcome.riv
    - assets/lottie/73969-rocket-flying.json
    - assets/lottie/89628-rocket-no-blackground.json
    - assets/lottie/lf30_editor_y3gijqdm.json
    - assets/lottie/106405-energy-rocket.json
    - assets/lottie/81045-rocket-launch.json
    - assets/lottie/lf30_editor_in1ne4w9.json
    - assets/lottie/lf30_editor_x3tmhtxh.json
    - assets/lottie/lf30_editor_vomrc8qf.json
    - assets/lottie/lf20_4cntnmut.json
    - assets/lottie/lf30_editor_wqxr1uwq.json
    - assets/lottie/lf30_editor_6akqllok.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raunchies
      fonts:
        - asset: fonts/RaunchiesDemoRegular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
